version: "2"
services:
  app:
    build: ./app
    container_name: "Final_App"
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    container_name: "MySQL_FinalApp"
    ports:
      - "39000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro